# Generated by Django 4.1.7 on 2023-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
    ]
