# Generated by Django 4.1.7 on 2023-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
