# Generated by Django 4.1.7 on 2023-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
