# Generated by Django 4.1.7 on 2023-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
