# Generated by Django 4.1.7 on 2023-04-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_description_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, null=True, unique=True),
        ),
    ]
