# Generated by Django 4.1.7 on 2023-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_phone_number_alter_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='skill',
            field=models.CharField(blank=True, choices=[('e', 'زبان انگلیسی'), ('g', 'زبان آلمانی')], max_length=200, null=True, verbose_name='Skill'),
        ),
    ]
