# Generated by Django 4.2.3 on 2023-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='skill',
            field=models.CharField(blank=True, choices=[('زبان آلمانی', 'g'), ('زبان انگلیسی', 'e')], max_length=200, null=True, verbose_name='Skill'),
        ),
    ]
