# Generated by Django 4.1.7 on 2023-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('days', models.CharField(max_length=200)),
                ('hour', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('e', 'English'), ('g', 'German')], max_length=1)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
