# Generated by Django 4.1.7 on 2023-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teachertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
