# Generated by Django 4.1.7 on 2023-03-21 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_teachertime_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='google_meet_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teachertime',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
