# Generated by Django 4.1.7 on 2023-04-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teachertime_google_meet_link_teachertime_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertime',
            name='date',
        ),
    ]
