# Generated by Django 4.1.7 on 2023-04-01 12:32

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_teachertime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
