# Generated by Django 4.1.7 on 2023-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_teachertime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='week_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
