# Generated by Django 4.1.7 on 2023-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_teachertime_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='gdate',
            field=models.DateField(null=True),
        ),
    ]
