# Generated by Django 4.1.7 on 2023-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_teachertime_student_alter_teachertime_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
