# Generated by Django 4.1.7 on 2023-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_teacherplan_plantime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='week_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
