# Generated by Django 4.1.7 on 2023-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_plantime_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherplan',
            name='google_meet_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacherplan',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
