# Generated by Django 4.1.7 on 2023-04-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_teacherplan_google_meet_link_teacherplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantime',
            name='week_day_number',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
