# Generated by Django 4.1.7 on 2023-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_plantime_week_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='week_day_number',
            field=models.IntegerField(null=True),
        ),
    ]
