# Generated by Django 4.1.7 on 2023-04-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_plantime_week_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='teacherplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeacherPlan', to='courses.teacherplan'),
        ),
    ]
