# Generated by Django 4.2.3 on 2023-07-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0020_alter_teachertime_student_alter_teachertime_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='teacherplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planTimes', to='courses.teacherplan'),
        ),
        migrations.AlterField(
            model_name='teacherplan',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
