# Generated by Django 4.2.3 on 2023-07-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_alter_plantime_teacherplan_alter_teacherplan_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherplan',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
