# Generated by Django 4.2.3 on 2023-09-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_sessions_number_order_start_date_and_more'),
        ('courses', '0022_alter_teacherplan_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantime',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_planTimes', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='plantime',
            name='teacherplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherPlan_planTimes', to='courses.teacherplan'),
        ),
    ]
