# Generated by Django 4.2.3 on 2023-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_order_status'),
        ('courses', '0023_plantime_order_alter_plantime_teacherplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantime',
            name='order',
        ),
        migrations.AddField(
            model_name='plantime',
            name='order',
            field=models.ManyToManyField(to='shop.order'),
        ),
    ]
