# Generated by Django 4.2.3 on 2023-09-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_status'),
        ('courses', '0024_remove_plantime_order_plantime_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantime',
            name='order',
        ),
        migrations.AddField(
            model_name='plantime',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_planTimes', to='shop.order'),
        ),
    ]
