# Generated by Django 4.2.3 on 2023-09-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_plantime_order_plantime_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantime',
            name='order',
        ),
    ]
