# Generated by Django 4.2.3 on 2023-09-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_order_teachertime_alter_order_status'),
        ('courses', '0026_remove_plantime_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertime',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_teacherTimes', to='shop.order'),
        ),
    ]
