# Generated by Django 4.2.3 on 2023-09-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_teachertime_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='teacherplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacherPlan_planTimes', to='courses.teacherplan'),
        ),
    ]
