# Generated by Django 4.2.3 on 2023-09-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_plantime_teacherplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantime',
            name='teacherplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherPlan_planTimes', to='courses.teacherplan'),
        ),
    ]
