# Generated by Django 4.1.7 on 2023-03-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
