# Generated by Django 4.1.7 on 2023-03-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
