# Generated by Django 4.1.7 on 2023-03-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mamad',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
