# Generated by Django 4.1.7 on 2023-03-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_course_mamad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mamad',
        ),
    ]
