# Generated by Django 4.1.7 on 2023-03-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_course_mamad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
