# Generated by Django 4.2.3 on 2024-05-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('c', 'complete'), ('i', 'incomplete'), ('p', 'pending')], default='incomplete', max_length=100, null=True)),
                ('total', models.BigIntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='courses.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('hour', models.CharField(blank=True, max_length=100, null=True)),
                ('minute', models.CharField(blank=True, max_length=100, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('card4Digits', models.CharField(blank=True, max_length=4, null=True)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transaction', to='shop.order')),
            ],
        ),
    ]
