# Generated by Django 4.2.3 on 2024-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'incomplete'), ('p', 'pending'), ('c', 'complete')], default='incomplete', max_length=100, null=True),
        ),
    ]
