# Generated by Django 4.1.7 on 2023-04-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_plantime_week_day_number'),
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='teacherTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeacherTime', to='courses.teachertime'),
        ),
    ]
