# Generated by Django 4.2.3 on 2023-07-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_teacherplan_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_orderitem_teachertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_orderItem', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='teacherTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherTime_orderItem', to='courses.teachertime'),
        ),
    ]
