# Generated by Django 4.2.3 on 2024-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course',
        ),
        migrations.AddField(
            model_name='order',
            name='courseId',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
