# Generated by Django 4.2.3 on 2023-07-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_teacherplan_teacher'),
        ('shop', '0007_alter_orderitem_teachertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='teacherTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherTime_orderItem', to='courses.teachertime'),
        ),
    ]
