# Generated by Django 4.2.3 on 2023-09-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_transaction_id_alter_order_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('hour', models.CharField(blank=True, max_length=100, null=True)),
                ('minute', models.CharField(blank=True, max_length=100, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('card4Digits', models.CharField(blank=True, max_length=4, null=True)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction', to='shop.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
