# Generated by Django 4.2.3 on 2023-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_complete_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('pending', 'pending'), ('incomplete', 'incomplete')], default='incomplete', max_length=100, null=True),
        ),
    ]
