# Generated by Django 4.2.3 on 2023-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_sessions_number_order_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sessions_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=100, null=True),
        ),
    ]
