# Generated by Django 4.2.3 on 2023-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_sessions_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('pending', 'pending'), ('complete', 'complete')], default='incomplete', max_length=100, null=True),
        ),
    ]
