# Generated by Django 4.2.3 on 2023-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_times',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('pending', 'pending')], default='incomplete', max_length=100, null=True),
        ),
    ]
