# Generated by Django 4.2.3 on 2023-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_plantime_order'),
        ('shop', '0018_order_plan_times_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='planTime',
            field=models.ManyToManyField(to='courses.plantime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('pending', 'pending'), ('complete', 'complete')], default='incomplete', max_length=100, null=True),
        ),
    ]
