# Generated by Django 4.2.3 on 2023-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_plantime_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='planTime',
            new_name='planTimes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan_times',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('pending', 'pending'), ('incomplete', 'incomplete')], default='incomplete', max_length=100, null=True),
        ),
    ]
