# Generated by Django 4.2.3 on 2023-09-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_plantime_order'),
        ('shop', '0020_rename_plantime_order_plantimes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='teacherTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherTime_order', to='courses.teachertime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
