# Generated by Django 4.2.3 on 2023-12-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('pending', 'pending'), ('incomplete', 'incomplete')], default='incomplete', max_length=100, null=True),
        ),
    ]
