# Generated by Django 4.2.3 on 2024-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('incomplete', 'incomplete'), ('pending', 'pending')], default='incomplete', max_length=100, null=True),
        ),
    ]
